[project]
name = "poople-engine"
version = "0.1.0"
description = "An engine to play the word ladder game poople optimally."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.2",
    "scipy>=1.18.1",
    "typer>=0.27.2",
]

[project.scripts]
poople = "engine.cli:main"
build = "engine.build:main"

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "pyinstaller>=6.22.3",
    "pytest>=9.1.1",
    "scipy-stubs>=1.18.1.0",
]

[tool.uv]
package = true
